### ISSUE TITLE
Instalacija po uputstvu nije moguća

### ISSUE THREAD

**Issue by imilos** [tmrdja/BlackFoxPython#7]
Instalacija direktno sa GitHuba:

`$ pip3 install git+https://github.com/tmrdja/BlackFoxPython.git --user
Collecting git+https://github.com/tmrdja/BlackFoxPython.git
  Cloning https://github.com/tmrdja/BlackFoxPython.git to /tmp/pip-req-build-zfyvi99j
Requirement already satisfied: urllib3>=1.15 in ./.local/lib/python3.7/site-packages (from blackfox==0.0.9) (1.23)
Requirement already satisfied: six>=1.10 in /usr/lib/python3.7/site-packages (from blackfox==0.0.9) (1.12.0)
Requirement already satisfied: certifi in ./.local/lib/python3.7/site-packages (from blackfox==0.0.9) (2018.11.29)
Requirement already satisfied: python-dateutil in /usr/lib/python3.7/site-packages (from blackfox==0.0.9) (2.8.0)
Collecting blackfox-restapi==0.0.1 (from blackfox==0.0.9)
  Could not find a version that satisfies the requirement blackfox-restapi==0.0.1 (from blackfox==0.0.9) (from versions: )
No matching distribution found for blackfox-restapi==0.0.1 (from blackfox==0.0.9)`

ili putem arhive:

`$ pip3 install ~/Downloads/blackfox-0.0.6.tar.gz --user
Processing ./Downloads/blackfox-0.0.6.tar.gz
Requirement already satisfied: urllib3>=1.15 in ./.local/lib/python3.7/site-packages (from blackfox==0.0.6) (1.23)
Requirement already satisfied: six>=1.10 in /usr/lib/python3.7/site-packages (from blackfox==0.0.6) (1.12.0)
Requirement already satisfied: certifi in ./.local/lib/python3.7/site-packages (from blackfox==0.0.6) (2018.11.29)
Requirement already satisfied: python-dateutil in /usr/lib/python3.7/site-packages (from blackfox==0.0.6) (2.8.0)
Building wheels for collected packages: blackfox
  Building wheel for blackfox (setup.py) ... done
  Stored in directory: /home/milos/.cache/pip/wheels/fb/c8/06/8d561d63055d3f680bba1600bf5c4de3950c70a1ffa35adfb7
Successfully built blackfox
blackfox-extras 0.0.1 has requirement blackfox>=0.0.8, but you'll have blackfox 0.0.6 which is incompatible.
`

**Comment by imilos** [comment]
Sada se instalira. Hvala! Nego, ostalo je samo `git+https://github.com/tmrdja/BlackFoxPython.git`, a treba git+https://github.com/vodena/BlackFoxPython.git.

**Comment by tmrdja** [comment]
Ispravljeno.
